version: "3.7"
services:
  airflow:
    build: ../../docker
    image: manning-airflow:latest
    ports:
      - "8080:8080"
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
    - ./other_scripts/listing_4_16.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  airflow:
